//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.9164
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using Metcom.CardPay3.Integration.Models.OneC;

// 
// Этот исходный код был создан с помощью xsd, версия=2.0.50727.3038.
// 
namespace Metcom.CardPay3.Integration.Models
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://v8.1c.ru/edi/edi_stnd/109")]
    [System.Xml.Serialization.XmlRootAttribute("СчетаПК", Namespace = "http://v8.1c.ru/edi/edi_stnd/109", IsNullable = false)]
    public partial class СчетПК
    {

        private object itemField;

        private string видЗачисленияField;

        private string кодВидаДоходаField;

        private string платежноеПоручениеField;

        private System.DateTime датаПлатежногоПорученияField;

        private bool датаПлатежногоПорученияFieldSpecified;

        private decimal комиссияРеестраField;

        private bool комиссияРеестраFieldSpecified;

        private КонтрольныеСуммы контрольныеСуммыField;

        private System.DateTime датаФормированияField;

        private string номерДоговораField;

        private System.DateTime датаДоговораField;

        private bool датаДоговораFieldSpecified;

        private string наименованиеОрганизацииField;

        private string иННField;

        private string расчетныйСчетОрганизацииField;

        private string бИКField;

        private string идПервичногоДокументаField;

        private string номерРеестраField;

        private System.DateTime датаРеестраField;

        private bool датаРеестраFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ЗачислениеЗарплаты", typeof(ЗачислениеЗарплаты))]
        [System.Xml.Serialization.XmlElementAttribute("ОткрытиеСчетов", typeof(ОткрытиеСчетов))]
        [System.Xml.Serialization.XmlElementAttribute("РезультатЗачисленияЗарплаты", typeof(РезультатЗачисленияЗарплаты))]
        [System.Xml.Serialization.XmlElementAttribute("РезультатОткрытияСчетов", typeof(РезультатОткрытияСчетов))]
        [System.Xml.Serialization.XmlElementAttribute("СписокУвольнений", typeof(СписокУвольнений))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public string ВидЗачисления
        {
            get
            {
                return this.видЗачисленияField;
            }
            set
            {
                this.видЗачисленияField = value;
            }
        }

        /// <remarks/>
        public string КодВидаДохода
        {
            get
            {
                return this.кодВидаДоходаField;
            }
            set
            {
                this.кодВидаДоходаField = value;
            }
        }

        /// <remarks/>
        public string ПлатежноеПоручение
        {
            get
            {
                return this.платежноеПоручениеField;
            }
            set
            {
                this.платежноеПоручениеField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime ДатаПлатежногоПоручения
        {
            get
            {
                return this.датаПлатежногоПорученияField;
            }
            set
            {
                this.датаПлатежногоПорученияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДатаПлатежногоПорученияSpecified
        {
            get
            {
                return this.датаПлатежногоПорученияFieldSpecified;
            }
            set
            {
                this.датаПлатежногоПорученияFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal КомиссияРеестра
        {
            get
            {
                return this.комиссияРеестраField;
            }
            set
            {
                this.комиссияРеестраField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КомиссияРеестраSpecified
        {
            get
            {
                return this.комиссияРеестраFieldSpecified;
            }
            set
            {
                this.комиссияРеестраFieldSpecified = value;
            }
        }

        /// <remarks/>
        public КонтрольныеСуммы КонтрольныеСуммы
        {
            get
            {
                return this.контрольныеСуммыField;
            }
            set
            {
                this.контрольныеСуммыField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаФормирования
        {
            get
            {
                return this.датаФормированияField;
            }
            set
            {
                this.датаФормированияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерДоговора
        {
            get
            {
                return this.номерДоговораField;
            }
            set
            {
                this.номерДоговораField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаДоговора
        {
            get
            {
                return this.датаДоговораField;
            }
            set
            {
                this.датаДоговораField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДатаДоговораSpecified
        {
            get
            {
                return this.датаДоговораFieldSpecified;
            }
            set
            {
                this.датаДоговораFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаименованиеОрганизации
        {
            get
            {
                return this.наименованиеОрганизацииField;
            }
            set
            {
                this.наименованиеОрганизацииField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИНН
        {
            get
            {
                return this.иННField;
            }
            set
            {
                this.иННField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РасчетныйСчетОрганизации
        {
            get
            {
                return this.расчетныйСчетОрганизацииField;
            }
            set
            {
                this.расчетныйСчетОрганизацииField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string БИК
        {
            get
            {
                return this.бИКField;
            }
            set
            {
                this.бИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдПервичногоДокумента
        {
            get
            {
                return this.идПервичногоДокументаField;
            }
            set
            {
                this.идПервичногоДокументаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерРеестра
        {
            get
            {
                return this.номерРеестраField;
            }
            set
            {
                this.номерРеестраField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаРеестра
        {
            get
            {
                return this.датаРеестраField;
            }
            set
            {
                this.датаРеестраField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДатаРеестраSpecified
        {
            get
            {
                return this.датаРеестраFieldSpecified;
            }
            set
            {
                this.датаРеестраFieldSpecified = value;
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
        [Serializable()]
        [System.Xml.Serialization.XmlType(Namespace = "http://v8.1c.ru/edi/edi_stnd/109", IncludeInSchema = false)]
        public enum ItemChoiceType
        {

            /// <remarks/>
            ЗачислениеЗарплаты,

            /// <remarks/>
            ОткрытиеСчетов,

            /// <remarks/>
            РезультатЗачисленияЗарплаты,

            /// <remarks/>
            РезультатОткрытияСчетов,

            /// <remarks/>
            СписокУвольнений
        }

    }
}
