name: .NET

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop"  ]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: https://gitea.com/actions/checkout@v3
    - name: Setup .NET
      uses: https://github.com/actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore CardPay3.sln
    - name: Build
      run: dotnet build CardPay3.sln --no-restore 
    - name: Test
      run: dotnet test CardPay3.sln --no-build --verbosity normal   